<a href="https://colab.research.google.com/github/rabinam24/NeuralNetworkFromScratch/blob/main/NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
inputs=[3.3,7.4,5]
weights=[4.1,4,7.8]
bias= 5

output= inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias

print(output)

87.13


In [3]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
# Neuron 1:
inputs[0]*weights1[0] +
inputs[1]*weights1[1] +
inputs[2]*weights1[2] +
inputs[3]*weights1[3] + bias1,
# Neuron 2:
inputs[0]*weights2[0] +
inputs[1]*weights2[1] +
inputs[2]*weights2[2] +
inputs[3]*weights2[3] + bias2,
# Neuron 3:
inputs[0]*weights3[0] +
inputs[1]*weights3[1] +
inputs[2]*weights3[2] +
inputs[3]*weights3[3] + bias3]

print(outputs)


[4.8, 1.21, 2.385]


In [4]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
[0.5, -0.91, 0.26, -0.5],
[-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# Output of current layer
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):

# Zeroed output of given neuron
  neuron_output = 0

# For each input and weight to the neuron
  for n_input, weight in zip(inputs, neuron_weights):

# Multiply this input by associated weight
# and add to the neuron’s output variable
    neuron_output += n_input*weight

# Add bias
  neuron_output += neuron_bias

# Put neuron’s result to the layer’s output list
  layer_outputs.append(neuron_output)
print(layer_outputs)


[4.8, 1.21, 2.385]


In [5]:
import numpy as np

In [6]:
inputs=[3.3,7.4,5]
weights=[4.1,4,7.8]
bias= 5

output= np.dot(inputs,weights) + bias
print(output)

87.13


In [7]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
[0.5, -0.91, 0.26, -0.5],
[-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output= np.dot(weights, inputs)+ biases
print(output)

[4.8   1.21  2.385]


In [8]:
# inputs = [1, 2, 3, 2.5]

# weights = [[0.2, 0.8, -0.5, 1],
# [0.5, -0.91, 0.26, -0.5],
# [-0.26, -0.27, 0.17, 0.87]]

# biases = [2, 3, 0.5]

# output= np.dot(inputs,weights)+ biases # here if we take the inputs first then weight it will so that error because of the shape. so we put weights first and then inputs
# print(output)

In [9]:
inputs = [[1, 2, 3, 2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

weights = [[0.2, 0.8, -0.5, 1],
[0.5, -0.91, 0.26, -0.5],
[-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output= np.dot(inputs,np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
